name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executes daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: XavierJoao
          outputs: github-contribution-grid-snake.svg  # Updated output file name
          
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: github-contribution-grid-snake.svg  # Path to the generated SVG
